import type { Metadata } from 'next'
import { Karla } from 'next/font/google'
import './globals.css'
import React from 'react'
import Providers from '@/providers/Providers'
import NekoPet from '@/components/neko-pet/NekoPet'

const karla = Karla({
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Weather App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={`${karla.className} bg-zin`}>
                <div className='antialiased'>
                    <Providers>
                        <NekoPet />
                        {children}
                    </Providers>
                </div>
            </body>
        </html>
    )
}
