import type { Metadata } from 'next'
import { Karla } from 'next/font/google'
import './globals.css'
import React from 'react'
import Providers from '@/providers/Providers'
import ToggleThemeButton from '@/components/ToggleThemeButton'

const karla = Karla({
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            {/* <Providers> */}
            <body className={`${karla.className} antialiased`}>
                <ToggleThemeButton />
                {children}
            </body>
            {/* </Providers> */}
        </html>
    )
}
